# Remote state backend values (generated by terraform-bootstrap).
bucket         = "wiz-exercise-tfstate-699475911107"
# Path/key within the bucket for this stack's state file.
key            = "wiz-exercise/terraform.tfstate"
# Region where the bucket and lock table exist.
region         = "us-east-1"
# DynamoDB table name used for state locking.
dynamodb_table = "wiz-exercise-tf-lock"
# Encrypt state objects at rest.
encrypt        = true
